# Generated by Django 3.1.2 on 2021-01-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad_description', models.CharField(default='', max_length=200)),
                ('cad_path', models.ImageField(default='', upload_to='img/cad/')),
            ],
        ),
        migrations.CreateModel(
            name='DepParams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_num', models.IntegerField(default=0)),
                ('dist_thre', models.IntegerField(default=-1)),
                ('spread_dist', models.IntegerField(default=0)),
                ('wall_reduce_dist', models.IntegerField(default=0)),
                ('glass_reduce_dist', models.IntegerField(default=0)),
                ('wood_reduce_dist', models.IntegerField(default=0)),
                ('other_reduce_dist', models.IntegerField(default=0)),
                ('time_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_path', models.ImageField(default='', upload_to='img/result/')),
                ('pos_path', models.FileField(default='', upload_to='csv/position_result/')),
                ('ap_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='headimg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.cad')),
                ('dep_param', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.depparams')),
                ('res', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.result')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
    ]
